### ISSUE TITLE
Epic #2: Upload documents + Show views

### ISSUE THREAD

**Issue by H-L** [bl-immo/glowing-guacamole#15]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by luknl** [comment]
Hey! Why don't we use this service to upload documents?
https://uppy.io/

**Comment by H-L** [comment]
Why not using Shrine, which Uppy out of the box ?
Need some review on this from @armandfardeau.
https://shrinerb.com/

**Comment by H-L** [comment]
Transloadit (creator of Uppy) also provides a rails-sdk, but Transloadit seems to be a freemium service...
https://github.com/transloadit/rails-sdk

**Comment by Tounaze** [comment]
*Product need* 
- Have the possibility to upload documents and see the success of this upload
- See a progress report in the completion of the rental file
- Be able to manage categories, documents and sub-documents (_eg_ payslip => first month pay slip => first month pay slip page 1 AND page 2)
- Have the possibility to see the documents upload (as C) without having to download
