### ISSUE TITLE
Please use docker for the project

### ISSUE THREAD

**Issue by luknl** [bl-immo/glowing-guacamole#9]
**Is your feature request related to a problem? Please describe.**
4 persons working on the project, with different env. Many dependencies problems

**Describe the solution you'd like**
Docker will solve that

**Describe alternatives you've considered**
Staying as it is, but docker is better

**Additional context**
I love whales and docks

**Comment by armandfardeau** [comment]
@luknl Would you like to work on this? This should be done asap ;)

**Comment by H-L** [comment]
Using `./bin/webpack-dev-server` might be way more accurate in dev / local set up.
I'll look at it as soon as I finish the navbar.
